#!/bin/sh

# @file check-monit-uptime
#
# Copyright (C) Metaswitch Networks 2016
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.

# Monit 5.8.1 does not support passing arguments to check program scripts.
# This wrapper script can be called with no arguments to clear the Monit alarm.
#
# By Monit calling this script, we can determine that Monit is alive,
# and so it is safe to clear the Monit alarm raised by upstart.
/usr/share/clearwater/bin/issue-alarm upstart 4500.1
